//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WTA_MECH.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double FormMSG_HT {
            get {
                return ((double)(this["FormMSG_HT"]));
            }
            set {
                this["FormMSG_HT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("280")]
        public double FormMSG_WD {
            get {
                return ((double)(this["FormMSG_WD"]));
            }
            set {
                this["FormMSG_WD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public double FormMSG_Top {
            get {
                return ((double)(this["FormMSG_Top"]));
            }
            set {
                this["FormMSG_Top"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public double FormMSG_Left {
            get {
                return ((double)(this["FormMSG_Left"]));
            }
            set {
                this["FormMSG_Left"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WTA Families")]
        public string RootSearchPath {
            get {
                return ((string)(this["RootSearchPath"]));
            }
            set {
                this["RootSearchPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>ST1_Workset</string>\r\n  <string>MECH HVAC</string>\r\n  <string>ST1_SensorFa" +
            "mily</string>\r\n  <string>M_BAS SENSOR</string>\r\n  <string>ST1_SensorFamilySymbol" +
            "</string>\r\n  <string>THERMOSTAT</string>\r\n  <string>ST1_IDParameter</string>\r\n  " +
            "<string>STAT ZONE NUMBER</string>\r\n  <string>ST1_SensorTagFamily</string>\r\n  <st" +
            "ring>M_EQIP_BAS_SENSOR_TAG</string>\r\n  <string>ST1_SensorTagFamilySymbol</string" +
            ">\r\n  <string>SENSOR</string>\r\n  <string>ST2_Workset</string>\r\n  <string>MECH HVA" +
            "C</string>\r\n  <string>ST2_SensorFamily</string>\r\n  <string>M_BAS SENSOR</string>" +
            "\r\n  <string>ST2_SensorFamilySymbol</string>\r\n  <string>THERMOSTAT</string>\r\n  <s" +
            "tring>ST2_IDParameter</string>\r\n  <string>STAT ZONE NUMBER</string>\r\n  <string>S" +
            "T2_SensorTagFamily</string>\r\n  <string>M_EQIP_BAS_SENSOR_TAG</string>\r\n  <string" +
            ">ST2_SensorTagFamilySymbol</string>\r\n  <string>TAG NUMBER ONLY</string>\r\n  <stri" +
            "ng>STO1_Workset</string>\r\n  <string>MECH HVAC</string>\r\n  <string>STO1_SensorFam" +
            "ily</string>\r\n  <string>M_BAS SENSOR</string>\r\n  <string>STO1_SensorFamilySymbol" +
            "</string>\r\n  <string>THERMOSTAT</string>\r\n  <string>STO1_IDParameter</string>\r\n " +
            " <string>STAT ZONE NUMBER</string>\r\n  <string>STO1_SensorTagFamily</string>\r\n  <" +
            "string>M_EQIP_BAS_SENSOR_TAG</string>\r\n  <string>STO1_SensorTagFamilySymbol</str" +
            "ing>\r\n  <string>SENSOR</string>\r\n  <string>STO1_SensorTagFamily2</string>\r\n  <st" +
            "ring>M_DEVICE_BAS_TAG_SYM</string>\r\n  <string>STO1_SensorTagFamilySymbol2</strin" +
            "g>\r\n  <string>M-DATA-SENSOR</string>\r\n  <string>STO2_Workset</string>\r\n  <string" +
            ">MECH HVAC</string>\r\n  <string>STO2_SensorFamily</string>\r\n  <string>M_BAS SENSO" +
            "R</string>\r\n  <string>STO2_SensorFamilySymbol</string>\r\n  <string>THERMOSTAT</st" +
            "ring>\r\n  <string>STO2_SensorTagFamily</string>\r\n  <string>M_EQIP_BAS_SENSOR_TAG<" +
            "/string>\r\n  <string>STO2_SensorTagFamilySymbol</string>\r\n  <string>TAG NUMBER ON" +
            "LY</string>\r\n  <string>STO2_SensorTagFamily2</string>\r\n  <string>M_DEVICE_BAS_TA" +
            "G_SYM</string>\r\n  <string>STO2_SensorTagFamilySymbol2</string>\r\n  <string>M-DATA" +
            "-SENSOR</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection SensorToolSettings {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["SensorToolSettings"]));
            }
            set {
                this["SensorToolSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public double SetMgr_Top {
            get {
                return ((double)(this["SetMgr_Top"]));
            }
            set {
                this["SetMgr_Top"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public double SetMgr_left {
            get {
                return ((double)(this["SetMgr_left"]));
            }
            set {
                this["SetMgr_left"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TagOtherViews {
            get {
                return ((bool)(this["TagOtherViews"]));
            }
            set {
                this["TagOtherViews"] = value;
            }
        }
    }
}
